version: '2.3'

services:

  app:
    build: .
    image: "blockchain"
    scale: 3
    ports:
      - 5001-5003:3000
  nginx:
    image: nginx:stable-alpine
    ports:
      - 5000:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx:/var/log/nginx
